### ISSUE TITLE
'include_top' cuts the network at the wrong spot

### ISSUE THREAD

**Issue by ialhashim** [titu1994/keras-SparseNet#3]
Shouldn't this call be made after the last BN?

https://github.com/titu1994/keras-SparseNet/blob/e07358c50017bd566745b375bc192880ff649b1e/sparsenet.py#L485

**Comment by titu1994** [comment]
Right. I'll fix it soon.

**Comment by ialhashim** [comment]
I also found the same issue at the SE network code https://github.com/titu1994/keras-squeeze-excite-network/blob/master/se_densenet.py#L444

Are these both based on an earlier implementation of Densenet? I found the performance of SparseNet very bad compared to latest Densenet code. I am now testing SE net which seem to give better performance than both. Is the code for that ready to train on imagenet? I would be happy to help in anyway to get it closer to integration into Keras applications repo.

**Comment by titu1994** [comment]
I reviewed the code and it is seemingly correct. I ordinarily add the option of choosing whether to pool or not, but these are custom models with no weights and I'm not adding them to contrib, so I didn't bother with adding it for them. 

If you want to get the full tensor without pooling, I suggest moving the pooling layer inside the if block. 

I've tried the authors sparsenet code as well, and performance is similarly quite poor on cifar 10. I was using a smaller ResNet 18 however, so that may be one of the reasons, but still I have not managed to get good performance out of sparsenet. It is probably due to the initial stride as well as max pool which reduces cifars size to 1x1 at the final stage. 

The code is a direct port of their implementation with same parameter defaults, so I don't know whether it's an implementation mistake on the original codebase or if I made some mistake in the port. 

SE codebase is proper but I encourage you to take the ResNet implementation from Tensorflow and add the se block there, rather than using the port here, as it will be able to benefit from faster performance on ImageNet.
